package com.common.system.entity;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class BlueStaff implements Serializable{
	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -9181290959426773152L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_staff.sid
	 * 
	 * @mbggenerated
	 */
	private Integer sid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_staff.name
	 * 
	 * @mbggenerated
	 */
	private String name;
	
	private String password;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_staff.job_num
	 * 
	 * @mbggenerated
	 */
	private String jobNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_staff.dept_id
	 * 
	 * @mbggenerated
	 */
	private Integer deptId;
	
	private String deptName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_staff.sex
	 * 
	 * @mbggenerated
	 */
	private int sex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_staff.phone
	 * 
	 * @mbggenerated
	 */
	private String phone;
	
	/**
	 * 地址
	 */
	private String address;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_staff.level
	 * 
	 * @mbggenerated
	 */
	private Integer level;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_staff.position_id
	 * 
	 * @mbggenerated
	 */
	private Integer positionId;
	
	private String positionName;
	
	private double callFee;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_staff.update_time
	 * 
	 * @mbggenerated
	 */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_staff.create_time
	 * 
	 * @mbggenerated
	 */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_staff.introduce
	 * 
	 * @mbggenerated
	 */
	private String introduce;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_staff.sid
	 * 
	 * @return the value of tb_blue_staff.sid
	 * 
	 * @mbggenerated
	 */
	public Integer getSid() {
		return sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_staff.sid
	 * 
	 * @param sid
	 *            the value for tb_blue_staff.sid
	 * 
	 * @mbggenerated
	 */
	public void setSid(Integer sid) {
		this.sid = sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_staff.name
	 * 
	 * @return the value of tb_blue_staff.name
	 * 
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_staff.name
	 * 
	 * @param name
	 *            the value for tb_blue_staff.name
	 * 
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_staff.job_num
	 * 
	 * @return the value of tb_blue_staff.job_num
	 * 
	 * @mbggenerated
	 */
	public String getJobNum() {
		return jobNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_staff.job_num
	 * 
	 * @param jobNum
	 *            the value for tb_blue_staff.job_num
	 * 
	 * @mbggenerated
	 */
	public void setJobNum(String jobNum) {
		this.jobNum = jobNum == null ? null : jobNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_staff.dept_id
	 * 
	 * @return the value of tb_blue_staff.dept_id
	 * 
	 * @mbggenerated
	 */
	public Integer getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_staff.dept_id
	 * 
	 * @param deptId
	 *            the value for tb_blue_staff.dept_id
	 * 
	 * @mbggenerated
	 */
	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	/**
	

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_staff.phone
	 * 
	 * @return the value of tb_blue_staff.phone
	 * 
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	public int getSex() {
		return sex;
	}

	public void setSex(int sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_staff.phone
	 * 
	 * @param phone
	 *            the value for tb_blue_staff.phone
	 * 
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_staff.level
	 * 
	 * @return the value of tb_blue_staff.level
	 * 
	 * @mbggenerated
	 */
	public Integer getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_staff.level
	 * 
	 * @param level
	 *            the value for tb_blue_staff.level
	 * 
	 * @mbggenerated
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_staff.position_id
	 * 
	 * @return the value of tb_blue_staff.position_id
	 * 
	 * @mbggenerated
	 */
	public Integer getPositionId() {
		return positionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_staff.position_id
	 * 
	 * @param positionId
	 *            the value for tb_blue_staff.position_id
	 * 
	 * @mbggenerated
	 */
	public void setPositionId(Integer positionId) {
		this.positionId = positionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_staff.update_time
	 * 
	 * @return the value of tb_blue_staff.update_time
	 * 
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_staff.update_time
	 * 
	 * @param updateTime
	 *            the value for tb_blue_staff.update_time
	 * 
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_staff.create_time
	 * 
	 * @return the value of tb_blue_staff.create_time
	 * 
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_staff.create_time
	 * 
	 * @param createTime
	 *            the value for tb_blue_staff.create_time
	 * 
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_staff.introduce
	 * 
	 * @return the value of tb_blue_staff.introduce
	 * 
	 * @mbggenerated
	 */
	public String getIntroduce() {
		return introduce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_staff.introduce
	 * 
	 * @param introduce
	 *            the value for tb_blue_staff.introduce
	 * 
	 * @mbggenerated
	 */
	public void setIntroduce(String introduce) {
		this.introduce = introduce == null ? null : introduce.trim();
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * @return the address
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * @param address the address to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * @return the positioName
	 */
	public String getPositionName() {
		return positionName;
	}

	/**
	 * @param positioName the positioName to set
	 */
	public void setPositionName(String positionName) {
		this.positionName = positionName;
	}

	/**
	 * @return the callFee
	 */
	public double getCallFee() {
		return callFee;
	}

	/**
	 * @param callFee the callFee to set
	 */
	public void setCallFee(double callFee) {
		this.callFee = callFee;
	}
	
	
	
	
}