package com.common.system.entity;

import java.util.Date;

public class BlueStaff {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_staff.sid
	 * 
	 * @mbggenerated
	 */
	private Integer sid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_staff.name
	 * 
	 * @mbggenerated
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_staff.job_num
	 * 
	 * @mbggenerated
	 */
	private String jobNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_staff.dept_id
	 * 
	 * @mbggenerated
	 */
	private Integer deptId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_staff.sex
	 * 
	 * @mbggenerated
	 */
	private Short sex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_staff.phone
	 * 
	 * @mbggenerated
	 */
	private String phone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_staff.level
	 * 
	 * @mbggenerated
	 */
	private Integer level;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_staff.position_id
	 * 
	 * @mbggenerated
	 */
	private Integer positionId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_staff.update_time
	 * 
	 * @mbggenerated
	 */
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_staff.create_time
	 * 
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_staff.introduce
	 * 
	 * @mbggenerated
	 */
	private String introduce;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_staff.sid
	 * 
	 * @return the value of tb_blue_staff.sid
	 * 
	 * @mbggenerated
	 */
	public Integer getSid() {
		return sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_staff.sid
	 * 
	 * @param sid
	 *            the value for tb_blue_staff.sid
	 * 
	 * @mbggenerated
	 */
	public void setSid(Integer sid) {
		this.sid = sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_staff.name
	 * 
	 * @return the value of tb_blue_staff.name
	 * 
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_staff.name
	 * 
	 * @param name
	 *            the value for tb_blue_staff.name
	 * 
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_staff.job_num
	 * 
	 * @return the value of tb_blue_staff.job_num
	 * 
	 * @mbggenerated
	 */
	public String getJobNum() {
		return jobNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_staff.job_num
	 * 
	 * @param jobNum
	 *            the value for tb_blue_staff.job_num
	 * 
	 * @mbggenerated
	 */
	public void setJobNum(String jobNum) {
		this.jobNum = jobNum == null ? null : jobNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_staff.dept_id
	 * 
	 * @return the value of tb_blue_staff.dept_id
	 * 
	 * @mbggenerated
	 */
	public Integer getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_staff.dept_id
	 * 
	 * @param deptId
	 *            the value for tb_blue_staff.dept_id
	 * 
	 * @mbggenerated
	 */
	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_staff.sex
	 * 
	 * @return the value of tb_blue_staff.sex
	 * 
	 * @mbggenerated
	 */
	public Short getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_staff.sex
	 * 
	 * @param sex
	 *            the value for tb_blue_staff.sex
	 * 
	 * @mbggenerated
	 */
	public void setSex(Short sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_staff.phone
	 * 
	 * @return the value of tb_blue_staff.phone
	 * 
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_staff.phone
	 * 
	 * @param phone
	 *            the value for tb_blue_staff.phone
	 * 
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_staff.level
	 * 
	 * @return the value of tb_blue_staff.level
	 * 
	 * @mbggenerated
	 */
	public Integer getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_staff.level
	 * 
	 * @param level
	 *            the value for tb_blue_staff.level
	 * 
	 * @mbggenerated
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_staff.position_id
	 * 
	 * @return the value of tb_blue_staff.position_id
	 * 
	 * @mbggenerated
	 */
	public Integer getPositionId() {
		return positionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_staff.position_id
	 * 
	 * @param positionId
	 *            the value for tb_blue_staff.position_id
	 * 
	 * @mbggenerated
	 */
	public void setPositionId(Integer positionId) {
		this.positionId = positionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_staff.update_time
	 * 
	 * @return the value of tb_blue_staff.update_time
	 * 
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_staff.update_time
	 * 
	 * @param updateTime
	 *            the value for tb_blue_staff.update_time
	 * 
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_staff.create_time
	 * 
	 * @return the value of tb_blue_staff.create_time
	 * 
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_staff.create_time
	 * 
	 * @param createTime
	 *            the value for tb_blue_staff.create_time
	 * 
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_staff.introduce
	 * 
	 * @return the value of tb_blue_staff.introduce
	 * 
	 * @mbggenerated
	 */
	public String getIntroduce() {
		return introduce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_staff.introduce
	 * 
	 * @param introduce
	 *            the value for tb_blue_staff.introduce
	 * 
	 * @mbggenerated
	 */
	public void setIntroduce(String introduce) {
		this.introduce = introduce == null ? null : introduce.trim();
	}
}