package com.common.system.entity;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class BlueDoctorSchedule implements Serializable{
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_doctor_schedule.sid
	 * 
	 * @mbggenerated
	 */
	private Integer sid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_doctor_schedule.staff_id
	 * 
	 * @mbggenerated
	 */
	private Integer staffId;
	
	private String staffName;
	private Integer deptId;
	private String deptName;
	

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_doctor_schedule.shift_id
	 * 
	 * @mbggenerated
	 */
	private String shiftTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_doctor_schedule.count
	 * 
	 * @mbggenerated
	 */
	private Integer count;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_doctor_schedule.update_time
	 * 
	 * @mbggenerated
	 */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_doctor_schedule.create_time
	 * 
	 * @mbggenerated
	 */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_doctor_schedule.sid
	 * 
	 * @return the value of tb_blue_doctor_schedule.sid
	 * 
	 * @mbggenerated
	 */
	public Integer getSid() {
		return sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_doctor_schedule.sid
	 * 
	 * @param sid
	 *            the value for tb_blue_doctor_schedule.sid
	 * 
	 * @mbggenerated
	 */
	public void setSid(Integer sid) {
		this.sid = sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_doctor_schedule.staff_id
	 * 
	 * @return the value of tb_blue_doctor_schedule.staff_id
	 * 
	 * @mbggenerated
	 */
	public Integer getStaffId() {
		return staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_doctor_schedule.staff_id
	 * 
	 * @param staffId
	 *            the value for tb_blue_doctor_schedule.staff_id
	 * 
	 * @mbggenerated
	 */
	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	/**
	 * @return the shiftTime
	 */
	public String getShiftTime() {
		return shiftTime;
	}

	/**
	 * @param shiftTime the shiftTime to set
	 */
	public void setShiftTime(String shiftTime) {
		this.shiftTime = shiftTime;
	}

	/**
	 * @return the staffName
	 */
	public String getStaffName() {
		return staffName;
	}

	/**
	 * @param staffName the staffName to set
	 */
	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	/**
	 * @return the deptId
	 */
	public Integer getDeptId() {
		return deptId;
	}

	/**
	 * @param deptId the deptId to set
	 */
	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	/**
	 * @return the deptName
	 */
	public String getDeptName() {
		return deptName;
	}

	/**
	 * @param deptName the deptName to set
	 */
	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_doctor_schedule.count
	 * 
	 * @return the value of tb_blue_doctor_schedule.count
	 * 
	 * @mbggenerated
	 */
	public Integer getCount() {
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_doctor_schedule.count
	 * 
	 * @param count
	 *            the value for tb_blue_doctor_schedule.count
	 * 
	 * @mbggenerated
	 */
	public void setCount(Integer count) {
		this.count = count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_doctor_schedule.update_time
	 * 
	 * @return the value of tb_blue_doctor_schedule.update_time
	 * 
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_doctor_schedule.update_time
	 * 
	 * @param updateTime
	 *            the value for tb_blue_doctor_schedule.update_time
	 * 
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_doctor_schedule.create_time
	 * 
	 * @return the value of tb_blue_doctor_schedule.create_time
	 * 
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_doctor_schedule.create_time
	 * 
	 * @param createTime
	 *            the value for tb_blue_doctor_schedule.create_time
	 * 
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}