package com.common.system.entity;

import java.util.Date;

public class BlueProject {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_project.sid
	 * 
	 * @mbggenerated
	 */
	private Integer sid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_project.name
	 * 
	 * @mbggenerated
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_project.update_time
	 * 
	 * @mbggenerated
	 */
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_project.create_time
	 * 
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_project.conetxt
	 * 
	 * @mbggenerated
	 */
	private String conetxt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_project.sid
	 * 
	 * @return the value of tb_blue_project.sid
	 * 
	 * @mbggenerated
	 */
	public Integer getSid() {
		return sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_project.sid
	 * 
	 * @param sid
	 *            the value for tb_blue_project.sid
	 * 
	 * @mbggenerated
	 */
	public void setSid(Integer sid) {
		this.sid = sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_project.name
	 * 
	 * @return the value of tb_blue_project.name
	 * 
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_project.name
	 * 
	 * @param name
	 *            the value for tb_blue_project.name
	 * 
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_project.update_time
	 * 
	 * @return the value of tb_blue_project.update_time
	 * 
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_project.update_time
	 * 
	 * @param updateTime
	 *            the value for tb_blue_project.update_time
	 * 
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_project.create_time
	 * 
	 * @return the value of tb_blue_project.create_time
	 * 
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_project.create_time
	 * 
	 * @param createTime
	 *            the value for tb_blue_project.create_time
	 * 
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_project.conetxt
	 * 
	 * @return the value of tb_blue_project.conetxt
	 * 
	 * @mbggenerated
	 */
	public String getConetxt() {
		return conetxt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_project.conetxt
	 * 
	 * @param conetxt
	 *            the value for tb_blue_project.conetxt
	 * 
	 * @mbggenerated
	 */
	public void setConetxt(String conetxt) {
		this.conetxt = conetxt == null ? null : conetxt.trim();
	}
}