package com.common.system.entity;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class BlueSource {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_source.sid
	 * 
	 * @mbggenerated
	 */
	private Integer sid;

	private String title;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_source.dept_id
	 * 
	 * @mbggenerated
	 */
	private Integer deptId;
	
	private String deptName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_source.position_id
	 * 
	 * @mbggenerated
	 */
	private Integer positionId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_source.update_time
	 * 
	 * @mbggenerated
	 */
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_source.create_time
	 * 
	 * @mbggenerated
	 */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_blue_source.context
	 * 
	 * @mbggenerated
	 */
	private String context;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_source.sid
	 * 
	 * @return the value of tb_blue_source.sid
	 * 
	 * @mbggenerated
	 */
	public Integer getSid() {
		return sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_source.sid
	 * 
	 * @param sid
	 *            the value for tb_blue_source.sid
	 * 
	 * @mbggenerated
	 */
	public void setSid(Integer sid) {
		this.sid = sid;
	}

	/**
	 * @return the title
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * @param title
	 *            the title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_source.dept_id
	 * 
	 * @return the value of tb_blue_source.dept_id
	 * 
	 * @mbggenerated
	 */
	public Integer getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_source.dept_id
	 * 
	 * @param deptId
	 *            the value for tb_blue_source.dept_id
	 * 
	 * @mbggenerated
	 */
	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}


	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_source.position_id
	 * 
	 * @return the value of tb_blue_source.position_id
	 * 
	 * @mbggenerated
	 */
	public Integer getPositionId() {
		return positionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_source.position_id
	 * 
	 * @param positionId
	 *            the value for tb_blue_source.position_id
	 * 
	 * @mbggenerated
	 */
	public void setPositionId(Integer positionId) {
		this.positionId = positionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_source.update_time
	 * 
	 * @return the value of tb_blue_source.update_time
	 * 
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_source.update_time
	 * 
	 * @param updateTime
	 *            the value for tb_blue_source.update_time
	 * 
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_source.create_time
	 * 
	 * @return the value of tb_blue_source.create_time
	 * 
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_source.create_time
	 * 
	 * @param createTime
	 *            the value for tb_blue_source.create_time
	 * 
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_blue_source.context
	 * 
	 * @return the value of tb_blue_source.context
	 * 
	 * @mbggenerated
	 */
	public String getContext() {
		return context;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_blue_source.context
	 * 
	 * @param context
	 *            the value for tb_blue_source.context
	 * 
	 * @mbggenerated
	 */
	public void setContext(String context) {
		this.context = context == null ? null : context.trim();
	}
}